### ISSUE TITLE
FreeCAD and Cura from repositoy are not working

### ISSUE THREAD

**Issue by beta-tester** [RPi-Distro/repo#235]
hi,
are all available packages at Raspberry Pi OS repository meant to run properly on a RPi?
(in my case RPi4B with 4GB)

**FreeCAD** is installing properly and starts with the splash screen. but when i try to create a 3D model, FreeCAD crashes
``` $ freecad
FreeCAD 0.18, Libs: 0.18R
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2019
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

libEGL warning: DRI2: failed to authenticate
Coin warning in cc_glglue_instance(): Error when setting up the GL context. This can happen if there is no current context, or if the context has been set up incorrectly.
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0xb3468120]
```

also **Cura** is installing properly and starts a splash screen and then with the agreements...
but then immediately it shows a crash report dialog.
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cura/Settings/MachineManager.py", line 970, in setSettingForAllExtruders
    for key, extruder in self._global_container_stack.extruders.items():
AttributeError: 'NoneType' object has no attribute 'extruders'
```

```
Thread 0x9cb93460 (most recent call first):
  File "/usr/lib/python3/dist-packages/UM/Backend/Backend.py", line 155 in _storeStderrToLogThread
  File "/usr/lib/python3.7/threading.py", line 865 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x9d394460 (most recent call first):
  File "/usr/lib/python3/dist-packages/UM/Backend/Backend.py", line 147 in _storeOutputToLogThread
  File "/usr/lib/python3.7/threading.py", line 865 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x9e49f460 (most recent call first):
  File "/usr/lib/cura/plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py", line 61 in _updateThread
  File "/usr/lib/python3.7/threading.py", line 865 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x9eca0460 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/threading.py", line 427 in acquire
  File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x9f4a1460 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/threading.py", line 427 in acquire
  File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x9fca2460 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/threading.py", line 427 in acquire
  File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0xa04a3460 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/threading.py", line 427 in acquire
  File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0xa0ce4460 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 300 in wait
  File "/usr/lib/python3/dist-packages/zeroconf.py", line 1794 in wait
  File "/usr/lib/python3/dist-packages/zeroconf.py", line 1365 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0xa14e5460 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 300 in wait
  File "/usr/lib/python3/dist-packages/zeroconf.py", line 1794 in wait
  File "/usr/lib/python3/dist-packages/zeroconf.py", line 1219 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0xa1ce6460 (most recent call first):
  File "/usr/lib/python3/dist-packages/zeroconf.py", line 1140 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0xa24e7460 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 300 in wait
  File "/usr/lib/python3.7/threading.py", line 552 in wait
  File "/usr/lib/cura/plugins/UM3NetworkPrinting/UM3OutputDevicePlugin.py", line 274 in _handleOnServiceChangedRequests
  File "/usr/lib/python3.7/threading.py", line 865 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0xa368b460 (most recent call first):
  File "/usr/lib/cura/plugins/USBPrinting/USBPrinterOutputDeviceManager.py", line 66 in _updateThread
  File "/usr/lib/python3.7/threading.py", line 865 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Current thread 0xb6f7ead0 (most recent call first):
  File "/usr/lib/python3/dist-packages/cura/CrashHandler.py", line 364 in _logInfoWidget
  File "/usr/lib/python3/dist-packages/cura/CrashHandler.py", line 214 in _createDialog
  File "/usr/lib/python3/dist-packages/cura/CrashHandler.py", line 82 in __init__
  File "/usr/bin/cura", line 101 in exceptHook
  File "/usr/lib/python3/dist-packages/UM/Qt/Bindings/ControllerProxy.py", line 98 in _onActiveStageChanged
  File "/usr/lib/python3/dist-packages/UM/Signal.py", line 315 in __performEmit
  File "/usr/lib/python3/dist-packages/UM/Signal.py", line 212 in emit
  File "/usr/lib/python3/dist-packages/UM/Controller.py", line 162 in setActiveStage
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 768 in runWithGUI
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 687 in run
  File "/usr/bin/cura", line 141 in <module>
```

**Comment by XECDesign** [comment]
Everything from the Raspberry Pi repo should, but the Raspbian repo is mostly just a rebuild of Debian for armv6-hf, so some things might not work and we have no control over that.

The FreeCAD issue has been reported upstream a long time ago, but I haven't seen any progress on it. No idea about the Cura issue.

If there's a patch for the the existing versions that fixes it, I can pull the package into our repo and apply it, but I haven't come across that.
