### ISSUE TITLE
Fail calibredb with --with-library

### ISSUE THREAD

**Issue by RandallRouth** [RPi-Distro/repo#257]
Command:
$ calibredb list --with-library=http://192.168.1.89:8080/#-
Yields:
Calibre_Library

Command:
calibredb list --with-library=http://192.168.1.89:8080/#Calibre_Library
Yields:
Traceback (most recent call last):
  File "/usr/bin/calibredb", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/db/cli/main.py", line 255, in main
    return run_cmd(cmd, opts, args[1:], DBCtx(opts))
  File "/usr/lib/calibre/calibre/db/cli/main.py", line 55, in run_cmd
    ret = m.main(opts, args, dbctx)
  File "/usr/lib/calibre/calibre/db/cli/cmd_list.py", line 324, in main
    for_machine=opts.for_machine
  File "/usr/lib/calibre/calibre/db/cli/cmd_list.py", line 150, in do_list
    ans = dbctx.run('list', fields, sort_by, ascending, search_text, limit)
  File "/usr/lib/calibre/calibre/db/cli/main.py", line 191, in run
    return self.remote_run(name, m, *args)
  File "/usr/lib/calibre/calibre/db/cli/main.py", line 213, in remote_run
    res = self.br.open_novisit(rq)
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 199, in open_novisit
    return self._mech_open(url, data, visit=False, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 230, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/usr/lib/python2.7/dist-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 344, in _open
    '_open', req)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 332, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1142, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1115, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1058, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1098, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1054, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 890, in _send_output
    msg += message_body
UnicodeDecodeError: 'utf8' codec can't decode byte 0x95 in position 0: invalid start byte

Command:
cat /etc/os-release 
Yields:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Command;
calibre --version
Yields:
calibre (calibre 3.39.1)

Command;
python --version
Yields:
Python 2.7.16

**Comment by XECDesign** [comment]
This issue tracker is for issues in packages which we maintain. I'm not familiar with calibre, nor does it come from our repo.

It's possible the issue will resolve itself once we release Bullseye, since it has a significantly newer version of Calibre. If not, then then it is most likely an issue that should be reported to Debian.
